//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Adminstrator
    {
     
        public string Admin_Name { get; set; }
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Nullable<int> Admin_National_Id { get; set; }
        public string Admin_Nationality { get; set; }
        public string Admin_password { get; set; }
        public string Admin_Username { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Phone { get; set; }
        public string ResetPasswordCode { get; set; }


    }




    public class AcceptanceInfoModel
    {
        public string ChildName { get; set; }
        public Nullable<int> ChildAge { get; set; }
        public int ChildNational_Id { get; set; }
        public string ChildNationality { get; set; }
        public string ChildGender { get; set; }
        public Nullable<System.DateTime> ChildBirthDate { get; set; }
        public int Cls_Id { get; set; }
        public int Monthl_Age { get; set; }
        public int Year_Age { get; set; }
        public string ParentName { get; set; }
        public int ParentNational_Id { get; set; }
        public string ParentNationality { get; set; }
        public string Parentpassword { get; set; }
        public string ParentUsername { get; set; }

    }

    public class ResetPasswordModel
    {
        [Required(ErrorMessage = "«œŒ· ﬂ·„… «·„—Ê— «·ÃœÌœ…", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }
        [Compare("NewPassword", ErrorMessage = "ﬂ·„… «·”— €Ì— „ ÿ«»ﬁ…")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required]
        public string ResetCode { get; set; }
    }

}
