//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Child
    {


        //public string Child_Name { get; set; }
        //public Nullable<int> Child_Age { get; set; }
        //[Key]
        //public int Child_National_Id { get; set; }
        //public string Child_Nationality { get; set; }
        //public string Child_Gender { get; set; }
        //public Nullable<System.DateTime> Child_BirthDate { get; set; }
        //public Nullable<int> Cls_Id { get; set; }
        //public Nullable<int> Mother { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Appointment> Appointments { get; set; }
        //public virtual Parent Parent { get; set; }
        //public virtual Class Class { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Delegation> Delegations { get; set; }



        public string Child_Name { get; set; }
        public Nullable<int> Child_Munth_Age { get; set; }
        public Nullable<int> Child_year_Age { get; set; }
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Child_National_Id { get; set; }
        public string Child_Nationality { get; set; }
        public string Child_Gender { get; set; }
		public string branch { get; set; }
		public Nullable<System.DateTime> Child_BirthDate { get; set; }

        public int Program_Id { get; set; }
        public Nullable<int> Mother { get; set; }

        public virtual Parent Parent { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delegation> Delegations { get; set; }
    }
}
