//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Delegation
    {
        [Key]
        public int id { get; set; }
        public Nullable<int> child_Id { get; set; }
        public Nullable<int> Parent_id { get; set; }
        public string Delegated_person_Name { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Delegated_person_id { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
