//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        [Key]
        public int Event_Number { get; set; }
        public string Event_Title { get; set; }
        public string Event_Description { get; set; }
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public DateTime? DOE { get; set; }
    }
}
