using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FAQ
    {
        [Key]
        public int FAQ_Number { get; set; }
        [DisplayName("السؤال")]
        [Required(ErrorMessage = "من فضلك ادخل السؤال")]
        public string FAQ_Question { get; set; }
        [DisplayName("الاجابة")]
        [Required(ErrorMessage = "من فضلك ادخل الاجابة")]
        public string FAQ_Answer { get; set; }
    }
}
