//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class File
    {
        
            public virtual int FileId { get; set; }
            [StringLength(255)]
            public virtual string FileName { get; set; }
            [StringLength(150)]
            public virtual string contentType { get; set; }
            public virtual byte[] content { get; set; }
         
      
    }
}
