//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Parent
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Parent()
        //{
        //    this.Appointments = new HashSet<Appointment>();
        //    this.Children = new HashSet<Child>();
        //}

        //public string Parent_Name { get; set; }
        //[Key]
        //public int Parent_National_Id { get; set; }
        //public string Parent_Nationality { get; set; }
        //public string Parent_password { get; set; }
        //public string Parent_Username { get; set; }
        //public string Parent_Email { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Appointment> Appointments { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Child> Children { get; set; }



        public string Parent_Name { get; set; }
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public  int  Parent_National_Id { get; set; }
        public string Parent_Nationality { get; set; }
        public string Parent_Email { get; set; }
        public Nullable<int> Parent_Phone { get; set; }
        public string Parent_password { get; set; }
        public string Parent_Username { get; set; }
        public string ResetPasswordCode { get; set; }
        public string Parent_state { get; set; }
        public string Parent_role { get; set; }
        public string Parent_College { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delegation> Delegations { get; set; }
    }
}
