using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Useful_Links
    {
        [Key]
        public int Link_Number { get; set; }
        [DisplayName("العنوان")]
        [Required(ErrorMessage = "من فضلك ادخل مسمى العنوان")]
        public string Link_Title { get; set; }
        [DisplayName("الرابط")]
        [Required(ErrorMessage = "من فضلك ادخل الرابط")]
        public string Link_href { get; set; }
    }
}
