//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminstrator
    {
        public int Admin_Id { get; set; }
        public string Admin_Name { get; set; }
        public Nullable<int> Admin_National_Id { get; set; }
        public string Admin_Nationality { get; set; }
        public string Admin_password { get; set; }
        public string Admin_Username { get; set; }
    }
}
