//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Blog_Number { get; set; }
        public string Blog_Content { get; set; }
        public Nullable<System.DateTime> Blog_CreatedAt { get; set; }
    }
}
