//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Child()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Delegations = new HashSet<Delegation>();
        }
    
        public string Child_Name { get; set; }
        public Nullable<int> Child_Age { get; set; }
        public int Child_National_Id { get; set; }
        public string Child_Nationality { get; set; }
        public string Child_Gender { get; set; }
        public Nullable<System.DateTime> Child_BirthDate { get; set; }
        public Nullable<int> Cls_Id { get; set; }
        public Nullable<int> Mother { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delegation> Delegations { get; set; }
    }
}
