//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Activity
    {
        public int Activity_number { get; set; }
        public Nullable<System.DateTime> Activity_date { get; set; }
        public string Activity_Description { get; set; }
    }
}
