//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STNSEntities : DbContext
    {
        public STNSEntities()
            : base("name=STNSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Adminstrator> Adminstrators { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Class_Activity> Class_Activity { get; set; }
        public virtual DbSet<Delegation> Delegations { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Nomination> Nominations { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Useful_Links> Useful_Links { get; set; }
        public virtual DbSet<Weekly_Task> Weekly_Task { get; set; }
    }
}
