//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomination
    {
        public int Child_Id { get; set; }
        public string Child_Fullname { get; set; }
        public string Child_Gender { get; set; }
        public System.DateTime Child_BirthDate { get; set; }
        public Nullable<int> Child_Age { get; set; }
        public string Child_Nationality { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_Nationality { get; set; }
        public Nullable<int> Mother_Phone { get; set; }
        public string Mother_Email { get; set; }
        public string Pranch { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public string Other { get; set; }
    }
}
