//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public virtual int PhotoId { get; set; }
        public virtual string PhotoTitle { get; set; }
        public virtual DateTime photoDate { get; set; }
        public virtual UserPhotoFile UserPhoto { get; set; }
        public virtual Album Album { get; set; }
        public virtual int? AlbumId { get; set; }
    }
}
