//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Teacher_Id { get; set; }
        public string Teacher_Name { get; set; }
        public Nullable<int> Teacher_National_Id { get; set; }
        public string Teacher_Nationality { get; set; }
        public string Teacher_password { get; set; }
        public string Teacher_Username { get; set; }
    }
}
